### ISSUE TITLE
[CRASH] Exception while updating neighbours

### ISSUE THREAD

**Issue by pog5** [SpaceWalkerRS/world-cutters#2]
Error Log: https://mclo.gs/skRyd0Z

**Comment by SpaceWalkerRS** [comment]
does it crash when you remove Carpet mod?

**Comment by pog5** [comment]
yep, still happens

**Comment by SpaceWalkerRS** [comment]
alright, the latest build is not compatible with 1.20.4 then

**Comment by pog5** [comment]
Issue seems to be related to this:
https://github.com/SpaceWalkerRS/world-cutters/blob/940386070fc44a903f071a41e604e14417802bcf/src/main/java/world/cutters/mixin/PistonStructureResolverMixin.java#L114

**Comment by SpaceWalkerRS** [comment]
ah right, I have a vague memory that Mojang did some refactors in that area and that class no longer exists - should be a simple fix then

**Comment by pog5** [comment]
as stated by the log,
```java
java.lang.NoClassDefFoundError: net/minecraft/class_4262
        at net.minecraft.class_2674.canBeBroken(class_2674.java:2114)
        at net.minecraft.class_2674.handler$djn000$world_cutters$undoBreakBlock(class_2674.java:2062)
```

With `net.minecraft.class_4262` being https://maven.fabricmc.net/docs/yarn-1.18.2-pre1+build.6/net/minecraft/block/AbstractGlassBlock.html according to google
